name: Build and test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore CalculatorSolution.sln

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild CalculatorSolution.sln /p:Configuration=Release /p:Platform=x64

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: out/Release/x64/CalculatorTests.exe
